### ISSUE TITLE
Error while running on a competitive match

### ISSUE THREAD

**Issue by Tresillo2017** [colinhartigan/ggsheet#6]
`Traceback (most recent call last):
  File "G:\ggsheet\main.py", line 31, in main
    builder.build_image()
  File "G:\ggsheet\src\image_builder.py", line 471, in build_image
    self.draw_header_footer()
  File "G:\ggsheet\src\image_builder.py", line 369, in draw_header_footer
    self.__draw_image(image,new_img)
  File "G:\ggsheet\src\image_builder.py", line 496, in __draw_image
    new_img = new_img.resize((new_width,new_height),Image.ANTIALIAS)
                                                    ^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'`

**Comment by aaron-sc** [comment]
I also have this issue!

AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
